# This file was generated by GoReleaser. DO NOT EDIT.
cask "cwctl-cli" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "41f41bb2bf4f920b08e90bb84c4cb1ba5dbf7bf7bdb1ddc7a87edc3c36bc866f"
      url "https://github.com/jjuanrivvera/cwctl/releases/download/v#{version}/cwctl_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "bdab24f77d2aaeaa557369d9bab62f9d48930c06f7d083d07f25962ae08342c5"
      url "https://github.com/jjuanrivvera/cwctl/releases/download/v#{version}/cwctl_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c06c8b74a42eb17582ad1b0fa4c42695bd0b7b23475f34af2bde3a8f85c6b41b"
      url "https://github.com/jjuanrivvera/cwctl/releases/download/v#{version}/cwctl_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "8c5b1a5c2b7df8c8964918e83cb57b5ed49a5e5bd9556900e3400a8c075fff04"
      url "https://github.com/jjuanrivvera/cwctl/releases/download/v#{version}/cwctl_#{version}_linux_arm64.tar.gz"
    end
  end

  name "cwctl-cli"
  desc ""
  homepage "https://github.com/jjuanrivvera/cwctl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cwctl"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cwctl"]
  end

  # No zap stanza required

end
