# This file was generated by GoReleaser. DO NOT EDIT.
cask "cwctl-cli" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "a3f1df9404c83eda13c05a2c7891144e503f7f40ed41f65c945921019a9ff482"
      url "https://github.com/jjuanrivvera/cwctl/releases/download/v#{version}/cwctl_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "12c543aa0644a8bb2e25a5aa4573fbdceed77737447e7f7cd946d30959afd792"
      url "https://github.com/jjuanrivvera/cwctl/releases/download/v#{version}/cwctl_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d4ccc220eb1ab1c8494a9e82b1438c71d9b4dfc2e260f0a7f6ae99ecba6ec9fb"
      url "https://github.com/jjuanrivvera/cwctl/releases/download/v#{version}/cwctl_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "5914adbbbf81722eef13a82833036c428fd6ca00d1c577716ca69acef3e24aa8"
      url "https://github.com/jjuanrivvera/cwctl/releases/download/v#{version}/cwctl_#{version}_linux_arm64.tar.gz"
    end
  end

  name "cwctl-cli"
  desc ""
  homepage "https://github.com/jjuanrivvera/cwctl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cwctl"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cwctl"]
  end

  # No zap stanza required

end
