# This file was generated by GoReleaser. DO NOT EDIT.
cask "cwctl-cli" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "149f26581e8ec153a45ea02c419672a53a3fc8fbcdab6650b478bc6d828a02cd"
      url "https://github.com/jjuanrivvera/cwctl/releases/download/v#{version}/cwctl_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "521f144a4918a916fb3576a4c31c9a587dd4ec9eff86f64f8fb29716e629ce21"
      url "https://github.com/jjuanrivvera/cwctl/releases/download/v#{version}/cwctl_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0e9533a172be260726c75d40102beb15c4ce8d25e4fb4f8b8e35064ad63157d8"
      url "https://github.com/jjuanrivvera/cwctl/releases/download/v#{version}/cwctl_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "3faf4c58805ad042c5fbf71838eecad5040ca17d1d039af0b688b4e99dfc2d84"
      url "https://github.com/jjuanrivvera/cwctl/releases/download/v#{version}/cwctl_#{version}_linux_arm64.tar.gz"
    end
  end

  name "cwctl-cli"
  desc ""
  homepage "https://github.com/jjuanrivvera/cwctl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cwctl"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cwctl"]
  end

  # No zap stanza required

end
