# This file was generated by GoReleaser. DO NOT EDIT.
cask "wootctl-cli" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "9893d8c48e052193b4bd33fa40c789cb7e4d145bf01d4cc50aa7134927815914"
      url "https://github.com/jjuanrivvera/wootctl/releases/download/v#{version}/wootctl_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "707a0ac95cf2c7a4da766bccd156aa0ca12f3debeeab5b16d5f51a55be6bc86d"
      url "https://github.com/jjuanrivvera/wootctl/releases/download/v#{version}/wootctl_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "30912aa5c877e8371fa7b146dc13a41ea4656c66eca24b7e9f80afd6b5155455"
      url "https://github.com/jjuanrivvera/wootctl/releases/download/v#{version}/wootctl_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "adfdc32d14767fe6ae787245c5417bef441509447ccaa0dc80b748bb5d44b265"
      url "https://github.com/jjuanrivvera/wootctl/releases/download/v#{version}/wootctl_#{version}_linux_arm64.tar.gz"
    end
  end

  name "wootctl-cli"
  desc ""
  homepage "https://github.com/jjuanrivvera/wootctl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wootctl"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/wootctl"]
  end

  # No zap stanza required

end
