# This file was generated by GoReleaser. DO NOT EDIT.
cask "wootctl-cli" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "c0475e02d8cac5675882cf0e5e477c4e7317971ea4361e73f0214b2991048be1"
      url "https://github.com/jjuanrivvera/wootctl/releases/download/v#{version}/wootctl_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "63ffd486e5c5f1b599cbf638e5ed1ca7cfaa698837a0d5c436e9516e4165af31"
      url "https://github.com/jjuanrivvera/wootctl/releases/download/v#{version}/wootctl_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a3dba96eb8a151d9505cc0d8c4282f86e8f405d8dff2e116b9d688f1ab0165e7"
      url "https://github.com/jjuanrivvera/wootctl/releases/download/v#{version}/wootctl_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "36d3b78cdd00a38edb293988f6ec359458f23c7c81d993e253ecdeeb83bebbd1"
      url "https://github.com/jjuanrivvera/wootctl/releases/download/v#{version}/wootctl_#{version}_linux_arm64.tar.gz"
    end
  end

  name "wootctl-cli"
  desc ""
  homepage "https://github.com/jjuanrivvera/wootctl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wootctl"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/wootctl"]
  end

  # No zap stanza required

end
