# This file was generated by GoReleaser. DO NOT EDIT.
cask "wootctl-cli" do
  version "0.3.1"

  on_macos do
    on_intel do
      sha256 "e22b937063d6c11e4d6f7c8c6a438ee762cecb4f085f84036ebc994ac761b80f"
      url "https://github.com/jjuanrivvera/wootctl/releases/download/v#{version}/wootctl_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "2730636c5141930b57114a4a252bc0c54a69d7d43594cc481e6e236354e27cd1"
      url "https://github.com/jjuanrivvera/wootctl/releases/download/v#{version}/wootctl_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d7cd7f6ed2f5b8ba3a0322f2edabca5348b8a294c8508de371f936f1d8dada97"
      url "https://github.com/jjuanrivvera/wootctl/releases/download/v#{version}/wootctl_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "390f3d21cf793921dfc0ddc04ab840135f8a3ed7e5102bc2d25c9cd1e6750ca4"
      url "https://github.com/jjuanrivvera/wootctl/releases/download/v#{version}/wootctl_#{version}_linux_arm64.tar.gz"
    end
  end

  name "wootctl-cli"
  desc ""
  homepage "https://github.com/jjuanrivvera/wootctl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wootctl"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/wootctl"]
  end

  # No zap stanza required

end
